name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'liberica'

      - name: give execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
  test:

    runs-on: ubuntu-latest

    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'liberica'
      - name: Give execute permission to gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew test

  executable:
    runs-on: ubuntu-latest

    needs: [build, test]
    steps:
      - name: Affiche la liste des fichiers
        run: echo ls -l
      - name: Build runnable JAR
        run: chmod +x ./gradlew && ./gradlew jar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'students management jar'
          path: build/libs/*.jar